import type { VaersRecord } from "./types";

/**
 * Hand-crafted mock VAERS dataset (50 records) for development and testing.
 *
 * Records are loosely modeled on real COVID-19 VAERS report patterns —
 * field shapes match the live dataset, symptoms reflect commonly reported
 * adverse events, but all VAERS IDs, narratives, and personal details are
 * fictional. This file is replaced by a real snapshot in Step 10.
 *
 * Deliberately includes patterns to exercise the matcher:
 *  - Cluster A (#01–#03): same state/sex/age, close vax dates → exact matches
 *  - Cluster B (#04–#06): same state/sex, ages within ±5 yrs → potentials
 *  - Solo serious-event records spread across years
 *  - U-sex and edge ages (pediatric, elderly)
 *  - Some records far from any plausible test input → no-match cases
 */
export const MOCK_VAERS_RECORDS: VaersRecord[] = [
  // ---- Cluster A: CA / F / 45, March 2021 ----
  {
    vaersId: "1000001",
    state: "CA",
    sex: "F",
    ageYears: 45,
    vaxDate: "2021-03-10",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Headache", "Fatigue", "Fever", "Pain in arm"],
    symptomText:
      "Patient reported severe headache and fatigue beginning approximately 12 hours after dose. Resolved within 48 hours.",
    recvDate: "2021-03-14",
    numDays: 1,
  },
  {
    vaersId: "1000002",
    state: "CA",
    sex: "F",
    ageYears: 45,
    vaxDate: "2021-03-12",
    vaxManu: "MODERNA",
    symptoms: ["Chills", "Myalgia", "Pyrexia"],
    symptomText:
      "Chills and muscle aches starting evening of vaccination, resolved by next morning.",
    recvDate: "2021-03-15",
    numDays: 1,
  },
  {
    vaersId: "1000003",
    state: "CA",
    sex: "F",
    ageYears: 46,
    vaxDate: "2021-03-15",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Anaphylaxis", "Urticaria", "Dyspnoea"],
    symptomText:
      "Anaphylactic reaction within 15 minutes of administration. Treated with epinephrine, observed for 4 hours, discharged.",
    recvDate: "2021-03-16",
    numDays: 0,
  },

  // ---- Cluster B: TX / M / ages 28-33, summer 2021 ----
  {
    vaersId: "1000004",
    state: "TX",
    sex: "M",
    ageYears: 28,
    vaxDate: "2021-06-04",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Myocarditis", "Chest pain"],
    symptomText:
      "Chest pain reported 3 days post-vaccination. Hospitalized, elevated troponin, diagnosed with mild myocarditis. Recovered fully.",
    recvDate: "2021-06-11",
    numDays: 3,
  },
  {
    vaersId: "1000005",
    state: "TX",
    sex: "M",
    ageYears: 31,
    vaxDate: "2021-06-15",
    vaxManu: "MODERNA",
    symptoms: ["Pericarditis", "Chest pain"],
    symptomText:
      "Reported sharp chest pain worsening with inspiration two days after second dose. Diagnosed with pericarditis on echo.",
    recvDate: "2021-06-20",
    numDays: 2,
  },
  {
    vaersId: "1000006",
    state: "TX",
    sex: "M",
    ageYears: 33,
    vaxDate: "2021-07-02",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Tachycardia", "Chest pain"],
    symptomText:
      "Episode of palpitations and chest tightness. Cardiology workup unremarkable. Symptoms resolved within a week.",
    recvDate: "2021-07-08",
    numDays: 4,
  },

  // ---- Mixed individual records ----
  {
    vaersId: "1000007",
    state: "NY",
    sex: "F",
    ageYears: 62,
    vaxDate: "2021-01-22",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Dizziness", "Syncope"],
    symptomText: "Patient fainted briefly 10 minutes after injection.",
    recvDate: "2021-01-24",
    numDays: 0,
  },
  {
    vaersId: "1000008",
    state: "FL",
    sex: "M",
    ageYears: 71,
    vaxDate: "2021-02-08",
    vaxManu: "MODERNA",
    symptoms: ["Pain in arm", "Lymphadenopathy"],
    symptomText:
      "Persistent axillary lymph node swelling on injection side, lasting ~2 weeks.",
    recvDate: "2021-02-22",
    numDays: 5,
  },
  {
    vaersId: "1000009",
    state: "PA",
    sex: "F",
    ageYears: 38,
    vaxDate: "2021-04-19",
    vaxManu: "JANSSEN",
    symptoms: ["Thrombosis", "Headache"],
    symptomText:
      "Cerebral venous sinus thrombosis confirmed on imaging 9 days after dose. Treated with anticoagulation.",
    recvDate: "2021-05-01",
    numDays: 9,
  },
  {
    vaersId: "1000010",
    state: "IL",
    sex: "F",
    ageYears: 29,
    vaxDate: "2021-05-12",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Fatigue", "Headache"],
    symptomText: "Mild flu-like symptoms day 1, resolved by day 2.",
    recvDate: "2021-05-14",
    numDays: 1,
  },
  {
    vaersId: "1000011",
    state: "OH",
    sex: "M",
    ageYears: 54,
    vaxDate: "2021-08-03",
    vaxManu: "MODERNA",
    symptoms: ["Fever", "Chills", "Myalgia"],
    symptomText: "Significant systemic reaction lasting 36 hours.",
    recvDate: "2021-08-07",
    numDays: 1,
  },
  {
    vaersId: "1000012",
    state: "GA",
    sex: "F",
    ageYears: 41,
    vaxDate: "2021-09-15",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Bell's palsy"],
    symptomText: "Unilateral facial droop noted 4 days after booster.",
    recvDate: "2021-09-22",
    numDays: 4,
  },
  {
    vaersId: "1000013",
    state: "NC",
    sex: "M",
    ageYears: 16,
    vaxDate: "2021-08-25",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Myocarditis", "Chest pain"],
    symptomText:
      "Adolescent male hospitalized with chest pain 2 days post-dose 2. Mild myocarditis diagnosed.",
    recvDate: "2021-08-29",
    numDays: 2,
  },
  {
    vaersId: "1000014",
    state: "MI",
    sex: "F",
    ageYears: 67,
    vaxDate: "2021-11-04",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Fatigue"],
    symptomText: "Booster dose. Tiredness for 24 hours.",
    recvDate: "2021-11-06",
    numDays: 1,
  },
  {
    vaersId: "1000015",
    state: "AZ",
    sex: "M",
    ageYears: 44,
    vaxDate: "2022-01-08",
    vaxManu: "MODERNA",
    symptoms: ["Tinnitus"],
    symptomText: "Onset of ringing in ears within 24 hours, ongoing at 30 days.",
    recvDate: "2022-02-09",
    numDays: 1,
  },
  {
    vaersId: "1000016",
    state: "WA",
    sex: "F",
    ageYears: 33,
    vaxDate: "2022-02-14",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Menstrual disorder"],
    symptomText:
      "Irregular menstrual cycles reported for three months following vaccination.",
    recvDate: "2022-05-10",
    numDays: 7,
  },
  {
    vaersId: "1000017",
    state: "MA",
    sex: "M",
    ageYears: 50,
    vaxDate: "2022-03-22",
    vaxManu: "MODERNA",
    symptoms: ["Guillain-Barre syndrome"],
    symptomText:
      "Ascending weakness and paresthesias beginning 11 days post-vaccination. Confirmed GBS on EMG.",
    recvDate: "2022-04-06",
    numDays: 11,
  },
  {
    vaersId: "1000018",
    state: "CO",
    sex: "F",
    ageYears: 24,
    vaxDate: "2022-04-11",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Headache", "Nausea"],
    symptomText: "Headache and nausea for 12 hours after dose.",
    recvDate: "2022-04-13",
    numDays: 0,
  },
  {
    vaersId: "1000019",
    state: "VA",
    sex: "M",
    ageYears: 78,
    vaxDate: "2022-05-30",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Pain in arm", "Fatigue"],
    symptomText: "Booster dose. Mild local reaction.",
    recvDate: "2022-06-02",
    numDays: 1,
  },
  {
    vaersId: "1000020",
    state: "OR",
    sex: "U",
    ageYears: 36,
    vaxDate: "2022-06-17",
    vaxManu: "NOVAVAX",
    symptoms: ["Pyrexia", "Myalgia"],
    symptomText: "Fever and body aches for 2 days.",
    recvDate: "2022-06-21",
    numDays: 1,
  },
  {
    vaersId: "1000021",
    state: "TN",
    sex: "M",
    ageYears: 60,
    vaxDate: "2022-08-04",
    vaxManu: "MODERNA",
    symptoms: ["Atrial fibrillation"],
    symptomText:
      "New-onset atrial fibrillation 5 days post-vaccination. Cardioverted, no recurrence at 60 days.",
    recvDate: "2022-08-12",
    numDays: 5,
  },
  {
    vaersId: "1000022",
    state: "IN",
    sex: "F",
    ageYears: 55,
    vaxDate: "2022-09-10",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Rash", "Pruritus"],
    symptomText: "Diffuse pruritic rash beginning 3 days post-injection.",
    recvDate: "2022-09-16",
    numDays: 3,
  },
  {
    vaersId: "1000023",
    state: "MO",
    sex: "M",
    ageYears: 22,
    vaxDate: "2022-10-15",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Syncope"],
    symptomText: "Brief loss of consciousness within 5 minutes of injection.",
    recvDate: "2022-10-17",
    numDays: 0,
  },
  {
    vaersId: "1000024",
    state: "MD",
    sex: "F",
    ageYears: 71,
    vaxDate: "2022-11-20",
    vaxManu: "MODERNA",
    symptoms: ["Dyspnoea", "Cough"],
    symptomText: "Shortness of breath and dry cough lasting 5 days.",
    recvDate: "2022-11-30",
    numDays: 2,
  },
  {
    vaersId: "1000025",
    state: "WI",
    sex: "M",
    ageYears: 49,
    vaxDate: "2023-01-09",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Headache", "Dizziness"],
    symptomText: "Bivalent booster. Mild reaction.",
    recvDate: "2023-01-11",
    numDays: 0,
  },
  {
    vaersId: "1000026",
    state: "MN",
    sex: "F",
    ageYears: 36,
    vaxDate: "2023-02-21",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Vertigo"],
    symptomText: "Episode of vertigo lasting several hours.",
    recvDate: "2023-02-23",
    numDays: 0,
  },
  {
    vaersId: "1000027",
    state: "SC",
    sex: "M",
    ageYears: 68,
    vaxDate: "2023-03-15",
    vaxManu: "MODERNA",
    symptoms: ["Fatigue", "Arthralgia"],
    symptomText: "Joint pain and tiredness for 4 days.",
    recvDate: "2023-03-21",
    numDays: 1,
  },
  {
    vaersId: "1000028",
    state: "AL",
    sex: "F",
    ageYears: 19,
    vaxDate: "2023-04-02",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Pain in arm"],
    symptomText: "Sore arm for 36 hours.",
    recvDate: "2023-04-04",
    numDays: 0,
  },
  {
    vaersId: "1000029",
    state: "LA",
    sex: "M",
    ageYears: 42,
    vaxDate: "2023-05-18",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Pulmonary embolism"],
    symptomText:
      "Pleuritic chest pain on day 6, CT angiogram positive for segmental PE. No identified risk factors.",
    recvDate: "2023-05-28",
    numDays: 6,
  },
  {
    vaersId: "1000030",
    state: "KY",
    sex: "F",
    ageYears: 50,
    vaxDate: "2023-06-30",
    vaxManu: "MODERNA",
    symptoms: ["Parosmia"],
    symptomText: "Altered sense of smell beginning 3 weeks post-vaccination.",
    recvDate: "2023-07-25",
    numDays: 21,
  },
  {
    vaersId: "1000031",
    state: "OK",
    sex: "M",
    ageYears: 26,
    vaxDate: "2023-07-12",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Migraine"],
    symptomText:
      "First-ever migraine episode 24 hours post-dose. Resolved with treatment.",
    recvDate: "2023-07-15",
    numDays: 1,
  },
  {
    vaersId: "1000032",
    state: "CT",
    sex: "F",
    ageYears: 81,
    vaxDate: "2023-08-22",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Fatigue", "Anorexia"],
    symptomText: "Reduced appetite and fatigue for 3 days.",
    recvDate: "2023-08-27",
    numDays: 1,
  },
  {
    vaersId: "1000033",
    state: "UT",
    sex: "M",
    ageYears: 39,
    vaxDate: "2023-09-14",
    vaxManu: "NOVAVAX",
    symptoms: ["Headache"],
    symptomText: "Mild headache for 24 hours.",
    recvDate: "2023-09-16",
    numDays: 0,
  },
  {
    vaersId: "1000034",
    state: "NV",
    sex: "F",
    ageYears: 28,
    vaxDate: "2023-10-06",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Tachycardia", "Anxiety"],
    symptomText: "Episode of rapid heart rate with anxiety symptoms.",
    recvDate: "2023-10-09",
    numDays: 1,
  },
  {
    vaersId: "1000035",
    state: "NM",
    sex: "M",
    ageYears: 64,
    vaxDate: "2023-10-28",
    vaxManu: "MODERNA",
    symptoms: ["Pain in arm"],
    symptomText: "Local injection-site soreness.",
    recvDate: "2023-10-30",
    numDays: 0,
  },
  {
    vaersId: "1000036",
    state: "IA",
    sex: "F",
    ageYears: 47,
    vaxDate: "2023-11-15",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Rash"],
    symptomText: "Localized rash at injection site lasting 5 days.",
    recvDate: "2023-11-21",
    numDays: 2,
  },
  {
    vaersId: "1000037",
    state: "KS",
    sex: "M",
    ageYears: 34,
    vaxDate: "2024-01-08",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Headache", "Fatigue"],
    symptomText: "Updated 2024 booster. Mild systemic reaction.",
    recvDate: "2024-01-10",
    numDays: 0,
  },
  {
    vaersId: "1000038",
    state: "AR",
    sex: "F",
    ageYears: 59,
    vaxDate: "2024-01-25",
    vaxManu: "MODERNA",
    symptoms: ["Pyrexia", "Chills"],
    symptomText: "Fever 38.5°C and chills for 18 hours.",
    recvDate: "2024-01-28",
    numDays: 1,
  },
  {
    vaersId: "1000039",
    state: "MS",
    sex: "M",
    ageYears: 73,
    vaxDate: "2024-02-12",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Confusion"],
    symptomText:
      "Episode of acute confusion lasting several hours. Workup negative. Returned to baseline.",
    recvDate: "2024-02-18",
    numDays: 1,
  },
  {
    vaersId: "1000040",
    state: "WV",
    sex: "F",
    ageYears: 31,
    vaxDate: "2024-03-04",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Dizziness"],
    symptomText: "Brief dizziness after injection, resolved within an hour.",
    recvDate: "2024-03-05",
    numDays: 0,
  },
  {
    vaersId: "1000041",
    state: "NE",
    sex: "M",
    ageYears: 8,
    vaxDate: "2022-07-19",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Pain in arm", "Pyrexia"],
    symptomText: "Pediatric patient. Mild fever and sore arm.",
    recvDate: "2022-07-22",
    numDays: 1,
  },
  {
    vaersId: "1000042",
    state: "ID",
    sex: "F",
    ageYears: 14,
    vaxDate: "2022-08-30",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Headache", "Fatigue"],
    symptomText: "Headache and fatigue for 24 hours.",
    recvDate: "2022-09-02",
    numDays: 1,
  },
  {
    vaersId: "1000043",
    state: "HI",
    sex: "M",
    ageYears: 57,
    vaxDate: "2021-10-05",
    vaxManu: "MODERNA",
    symptoms: ["Vaccine breakthrough infection"],
    symptomText:
      "COVID-19 infection diagnosed 2 weeks post-booster. Mild illness.",
    recvDate: "2021-10-25",
    numDays: 14,
  },
  {
    vaersId: "1000044",
    state: "AK",
    sex: "F",
    ageYears: 43,
    vaxDate: "2021-12-11",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Anaphylaxis"],
    symptomText:
      "Hypotension, urticaria, and wheezing within 10 minutes of injection. Treated and discharged same day.",
    recvDate: "2021-12-12",
    numDays: 0,
  },
  {
    vaersId: "1000045",
    state: "ME",
    sex: "M",
    ageYears: 67,
    vaxDate: "2022-03-08",
    vaxManu: "MODERNA",
    symptoms: ["Herpes zoster"],
    symptomText: "Shingles outbreak diagnosed 12 days post-vaccination.",
    recvDate: "2022-03-25",
    numDays: 12,
  },
  {
    vaersId: "1000046",
    state: "RI",
    sex: "F",
    ageYears: 52,
    vaxDate: "2022-04-29",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Insomnia"],
    symptomText: "Several nights of insomnia following booster.",
    recvDate: "2022-05-04",
    numDays: 1,
  },
  {
    vaersId: "1000047",
    state: "NH",
    sex: "M",
    ageYears: 37,
    vaxDate: "2022-06-21",
    vaxManu: "MODERNA",
    symptoms: ["Pain in arm", "Fatigue", "Headache"],
    symptomText: "Common systemic reaction following dose 3.",
    recvDate: "2022-06-23",
    numDays: 0,
  },
  {
    vaersId: "1000048",
    state: "VT",
    sex: "F",
    ageYears: 25,
    vaxDate: "2023-02-09",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Palpitations"],
    symptomText: "Intermittent palpitations for 1 week post-vaccination.",
    recvDate: "2023-02-18",
    numDays: 1,
  },
  {
    vaersId: "1000049",
    state: "DE",
    sex: "U",
    ageYears: 41,
    vaxDate: "2023-05-04",
    vaxManu: "PFIZER\\BIONTECH",
    symptoms: ["Headache"],
    symptomText: "Mild headache, resolved within 12 hours.",
    recvDate: "2023-05-05",
    numDays: 0,
  },
  {
    vaersId: "1000050",
    state: "MT",
    sex: "F",
    ageYears: 88,
    vaxDate: "2023-11-02",
    vaxManu: "MODERNA",
    symptoms: ["Fatigue"],
    symptomText: "Two days of tiredness following dose.",
    recvDate: "2023-11-06",
    numDays: 1,
  },
];

/**
 * Metadata about the mock dataset, mirroring what real R2-hosted data
 * will eventually carry.
 */
export const MOCK_VAERS_METADATA = {
  source: "mock",
  recordCount: MOCK_VAERS_RECORDS.length,
  generatedAt: "2024-04-01T00:00:00Z",
  coverageStart: "2021-01-01",
  coverageEnd: "2024-03-31",
} as const;
